version: '3.4'

services:
  app:
    build:
      context: .
      target: symfony_docker_php
    env_file:
      - .env
    restart: unless-stopped
    healthcheck:
      interval: 10s
      timeout: 3s
      retries: 3
      start_period: 30s
    ports:
      - 9000:9000

  nginx:
    build:
      context: .
      target: symfony_docker_nginx
    depends_on:
      - app
    volumes:
      # Comment out the next line in production
      - ./docker/nginx/conf.d:/etc/nginx/conf.d
      - ./public:/srv/app/public
    ports:
      - 80:80
